name: ChatMunger
version: 1.1.0
author: F1shb0ne
main: ca.vire.ChatMunger.Plugin
commands:
   speak:
      description: Munged chat command
      usage: /speak
      permission: ChatMunger.speak
      permission-message: §4You are not able to speak munged languages.
   lang:
      description: Switch to another language
      usage: /lang
      permission: ChatMunger.lang
      permission-message: §4You are not able to switch languages.
   teachlang:
      description: Lets a player teach another player a language
      usage: /teachlang
      permission: ChatMunger.teachlang
      permission-message: §4You are not able to teach munged languages.
   acceptlang:
      description: Accept a teaching offer from another player
      usage: /acceptlang
      permission: ChatMunger.acceptlang
      permission-message: §4You are not able to accept munged language teachings.
   givelang:
      description: Instantly gives a player use of a language
      usage: /givelang
      permission: ChatMunger.givelang
      permission-message: §4You are not allowed to do that.
   langinfo:
      description: Gives information about languages and what the player knows.
      usage: /langinfo
      permission: ChatMunger.langinfo
      permission-message: §4You are not able to get info on languages.
   langreload:
      description: Reloads language files in plugin data folder.
      usage: /langreload
      permission: ChatMunger.langreload
      permission-message: §4You are not allowed to do that.

